name: bank_salamu_master
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  another_flushbar: ^1.10.28
  carousel_slider: ^4.0.0
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  #flutter_secure_storage: ^5.0.2
  google_fonts: ^4.0.0
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  url_launcher: ^6.1.11
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
 
